# Gradient Descent

In [2]:
import torch
import torch.nn.functional as F

In [3]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [8]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.2759, 0.2134, 0.5695],
        [0.9993, 0.5222, 0.6267],
        [0.4802, 0.7211, 0.1802]], requires_grad=True)

In [9]:
x.grad

In [10]:
loss = F.mse_loss(x, target)

loss

tensor(0.1152, grad_fn=<MseLossBackward0>)

In [11]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad
    
    # You don't need to aware this now.
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

tensor([[ 0.0391,  0.0030,  0.0599],
        [ 0.1332,  0.0049,  0.0059],
        [-0.0489, -0.0175, -0.1600]])
1-th Loss: 6.9687e-02
tensor([[0.2368, 0.2104, 0.5096],
        [0.8661, 0.5172, 0.6207],
        [0.5290, 0.7386, 0.3402]], requires_grad=True)
tensor([[ 0.0304,  0.0023,  0.0466],
        [ 0.1036,  0.0038,  0.0046],
        [-0.0380, -0.0136, -0.1244]])
2-th Loss: 4.2156e-02
tensor([[0.2064, 0.2081, 0.4630],
        [0.7625, 0.5134, 0.6161],
        [0.5670, 0.7522, 0.4646]], requires_grad=True)
tensor([[ 0.0236,  0.0018,  0.0362],
        [ 0.0806,  0.0030,  0.0036],
        [-0.0296, -0.0106, -0.0968]])
3-th Loss: 2.5502e-02
tensor([[0.1827, 0.2063, 0.4268],
        [0.6820, 0.5104, 0.6125],
        [0.5966, 0.7629, 0.5613]], requires_grad=True)
tensor([[ 0.0184,  0.0014,  0.0282],
        [ 0.0627,  0.0023,  0.0028],
        [-0.0230, -0.0083, -0.0753]])
4-th Loss: 1.5427e-02
tensor([[0.1644, 0.2049, 0.3986],
        [0.6193, 0.5081, 0.6098],
        [0.6196, 0.7711, 0.